### ISSUE TITLE
ES5 Benchmark not working after change in Matcher class

### ISSUE THREAD

**Issue by mroeder** [harc/ohm#176]
`./bin/es5bench` does not work in the latest version anymore and fails with:

```
/src/Matcher.js:35
  var newValues = Array.apply(null, new Array(str.length));  // Array of `undefined` (wat)
                        ^

RangeError: Maximum call stack size exceeded
    at Matcher.replaceInput (/src/Matcher.js:35:25)
    at Object.Grammar.match (/src/Grammar.js:88:7)
    at /examples/ecmascript/compile.js:75:31
    at Array.every (native)
    at compile (/examples/ecmascript/compile.js:72:25)
    at Object.<anonymous> (/examples/ecmascript/compile.js:102:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

`git bisect` said it all went wrong in 7083ea996ddca8bac626d9a011983be70879919d - "refactoring: add Matcher class" (before it already had trouble with the second phase, code generation, but at least the matcher worked).

**Comment by alexwarth** [comment]
Commit 5233e81 fixes the main problem, but the ES5 benchmark still doesn't work b/c we're running out of memory.

**Comment by mroeder** [comment]
I did a bisect again and 9f144531813ff563d2ae2cffe225b8d5d3bad8f9 seems to be the commit that introduced the memory problem. Before that, everything was fine, afterwards the codegen phase wouldn't work anymore, even later parsing would fail (working again after the fix by @alexwarth, s.a.).

**Comment by pdubroy** [comment]
@mroeder: Thanks for bisecting! I'll work on a fix.

**Comment by pdubroy** [comment]
So turning `asES5` into an operation (and eliminating the `modifiedSource` attribute) didn't seem to make a difference. I guess this means that V8 does indeed do the smart thing, and doesn't create a new, contiguous character array when you concatenate strings.

I tried running with Node's `--trace_gc` option to compare the memory usage between the current version and the last version that worked. Here's the output from the last few GCs before we run out of memory:

```
32460 ms: Mark-sweep 1370.9 (1434.3) -> 1370.6 (1434.3) MB, 1345.9 / 0 ms [allocation failure] [GC in old space requested].
33791 ms: Mark-sweep 1370.6 (1434.3) -> 1370.6 (1434.3) MB, 1330.7 / 0 ms [allocation failure] [GC in old space requested].
35116 ms: Mark-sweep 1370.6 (1434.3) -> 1370.5 (1434.3) MB, 1325.0 / 0 ms [last resort gc].
36437 ms: Mark-sweep 1370.5 (1434.3) -> 1370.5 (1434.3) MB, 1321.0 / 0 ms [last resort gc].
```

And here's the last GC from a successful run:

```
29606 ms: Scavenge 1331.7 (1384.2) -> 1321.8 (1387.2) MB, 26.7 / 0 ms (+ 44.3 ms in 202 steps since last GC) [allocation failure].
```

The numbers to note are 1370.5 vs. 1331.7. That's the amount of used heap space. So we were running quite close to the limit before. With 9f14453 we use just less than 40MB more.

There are just under 1M CST nodes (I counted 963971), so if my change resulted in 40 more bytes per node, that would account for the difference. My change adds one more Array per CST node (`childOffsets`), and from what I understand about V8's object layout, those will take up a minimum of 32 bytes (3 slots for the object header, plus a length field, all 64 bits). The pointer from the CST node to the Array is another 8 bytes, so that's 40 bytes per object -- which nicely adds up to almost exactly 40MB of extra heap space.

So, now that I feel convinced that there isn't something majorly wrong happening, I'll see what I can do to fix this :-)

**Comment by pdubroy** [comment]
The ES5 benchmark works now, but we don't have much breathing room -- peak memory usage is still about 1365MB. If the memory usage becomes a problem again, I think we have a few more options:

- It looks like we don't need the `grammar` field in every node, as its only used on the root node
- For a bigger win, I think we might be able to drop TerminalNode altogether, and just use strings as the leaf CST nodes. This would require a few `typeof` checks, and could break some user code, but it might be a pretty big win in terms of memory usage, and I suspect it would improve raw compilation speed too.
