### ISSUE TITLE
How to pass extra arguments to a semantic action?

### ISSUE THREAD

**Issue by kkeri** [harc/ohm#195]
I would like to write a semantic operation that would build a symbol table. I have no idea how to pass "global" information to a semantic action. I guess this has to do with *operations with arguments / inherited attributes* which are on your todo list.
Actually I could build the table bottom-up, merging child tables in each parent. (*edit:* but even then how can I access the complete symbol table from each node?)
Can you give me a hint how to deal with this task?

**Comment by pdubroy** [comment]
You can create an operation that takes an argument like this (assuming a grammar `g`):

```
g.createSemantics().addOperation('foo(x, y)', {
  ...
});
```

Inside a semantic action, the arguments are available as `this.args.x` and `this.args.y`. When invoking the operation on a child node, the arguments are passed just like regular method arguments -- e.g., `childNode.foo(3, 4)`.

Hope that answers your question.

(BTW, I think the [mailing list](https://groups.google.com/a/ycr.org/forum/#!forum/ohm) is the best place for questions like this, so that other users will be more likely to see it.)

**Comment by kkeri** [comment]
Thank you, this is what I needed. 
I checked out the mailing list and in the future I will direct my questions there.
