### ISSUE TITLE
Postinstall script fails on Windows 7

### ISSUE THREAD

**Issue by Diorbert** [harc/ohm#205]
I'm trying to install ohm-js on Windows 7, but fails with the following error:

```
ohm-js@0.13.1 postinstall: `bash bin/postinstall`

Failed at the ohm-js@0.13.1 postinstall script 'bash bin/postinstall'.
Make sure you have the latest version of node.js and npm installed.
```
I checked the Issues History and found the Issue #42 , which treated the same problem, but didn't solved to me.

**Comment by thisiskell** [comment]
I am running into the same issue.

**Comment by mniebling** [comment]
Would you be open to implementing the npm postinstall functionality with Node scripts instead? As described in [this thread](https://github.com/npm/npm/issues/6543#issuecomment-60190760) I think this would get you the best portability.

Since it looks like the main goal of the postinstall hook is to add a git hook for developers, perhaps using [husky](https://github.com/typicode/husky) as a `devDependency` might also be an option? I've had good results with that, although mainly for simple `"precommit: npm test"` type hooks.

**Comment by pdubroy** [comment]
Since none of the core developers are using Windows, I'd be happy to take a PR that will fix these problems (as long as the solution isn't too complicated, that is).

@mniebling: Moving to Husky seems like it might be a good idea. Would you like to submit a PR?

**Comment by mniebling** [comment]
Yes, I'm happy to take a look at this. We're using Ohm at work and our dev machines are a mix of OS so I should be able to get some free testers 😄

**Comment by pdubroy** [comment]
Great, thanks! BTW I'd love to hear what you are using Ohm for; feel free to email me privately (address is in my profile).

**Comment by Diorbert** [comment]
Good to know that I am not the only one still with this problem, but I would like to share something. I was able to work around the problem by installing a linux terminal emulator (cmder). With that it worked for me. :smiley:
