### ISSUE TITLE
Improve detection of infinite loops

### ISSUE THREAD

**Issue by halffullheart** [harc/ohm#207]
I was editing a script in Chrome when the page completely froze, then crashed.

To reproduce:

1. Paste in this grammar:
```
MyGrammar {

  List = "(" ListOf<number, ""> ")"

  number = digit *

}
```

2. Try typing in an example, like `(1, 23, 456)`

I was also able to reproduce this in node with the following:
```
const ohm = require('ohm-js');

const myGrammar = ohm.grammar(`MyGrammar {

  List = "(" ListOf<number, ""> ")"

  number = digit *

}`);

const match = myGrammar.match('(1, 23, 456)');

console.log(match.succeeded());
```

Note that you can fix the grammar by adding in the missing comma inside the quotes in the second argument to `ListOf`. Maybe the empty string isn’t valid, but it should probably not cause a crash either in node or in the browser where you could just be deleting the comma to change the delimiter.

Node 6.50, ohm 0.13.1, Chrome 59.0.3071.115 for macOS

**Comment by pdubroy** [comment]
Thanks for reporting this!

The problem is that the grammar causes matching to go into an infinite loop, because:

- `number` is defined as `digit*`, so will succeed no matter what (even if it consumes 0 characters)
- After matching the first number, the remaining input is `, 23, 456` — then, since both `number` and the separator (2nd arg to `ListOf`) consume nothing, it will just continuously alternate between the two but never make any progress

We have some static checks that detect and prevent some kinds of infinite loop, but clearly not this one. I agree that it would be nice if we could handle this better...but I'll have to think a bit more how to do so.

**Comment by pdubroy** [comment]
After a quick look at `pexprs-isNullable.js`, it's not clear to me why we're not detecting this case statically.

**Comment by pdubroy** [comment]
This is the same as #211.
