### ISSUE TITLE
ListOf with empty separator causes a crash

### ISSUE THREAD

**Issue by crackcomm** [harc/ohm#209]
This is not important but anyway. `ListOf<elem, "">` causes a crash.
Be careful when trying this with local storage in online ;)

**Comment by alexwarth** [comment]
Hi Lukasz,

`ListOf<elem, sep>` is implemented as `elem (sep elem)*`. So it should be fine to pass a nullable expression as the separator (i.e., a separator that is willing to succeed w/o consuming any input) *or* a nullable expression for the element argument, but not both.

I suspect that in your example, the element argument was also nullable, but I can't be sure without seeing the whole thing. Would you mind posting it here?

Also, I just tried `ListOf<"a", "">` and it worked as expected. 

Cheers,
Alex

**Comment by crackcomm** [comment]
Hey, thanks for the answer.

I was quite sure it was the reason, sorry for not being more specific.

Here is the grammar that causes the crash:

```ohm
Cells {
  Cell = Path Body?
  Body = "{" ListOf<Cell, ""> "}"
  Path = ListOf<Name, PathDelimeter>
  PathDelimeter = "."
  Name = (alnum | "_")+
}
```

I have no idea which example crashes but here is the exported [JSON](https://gist.github.com/crackcomm/3067b1eed8ac966e994b88c0e1a87fd4).

**Comment by alexwarth** [comment]
Right, the problem is that `Cell` is nullable (because `Path`s can be empty and `Body` is not required). Then in `Body`, you have `ListOf<Cell, "">` and since `Cell` is nullable, that iteration will never terminate. I think you need to rethink your grammar a little bit.

BTW you could have written that expression more simply as `Cell*`, and if you had, Ohm would have complained that you've applied a Kleene-* to a nullable expression. (Try it!) It would be great to also have these static checks for rule applications, but that's not something we can do modularly -- it would require a whole program analysis, including all of the supergrammars, etc.

**Comment by crackcomm** [comment]
When I tried `Cell*` compiler complained about infinite loops so I tried `ListOf`.
I am just trying `ohm`, my use case is just a prototype and if not ohm I wouldn't waste my time. Thank you :)

**Comment by pdubroy** [comment]
I'm late to the party here, but can you clarify what the "crash" was? Was this in the Ohm Editor, or running in Node, or ...?

I wonder if we should implement some kind of infinite loop detection...either in Ohm itself, or in the editor. Alex, what do you think?

**Comment by alexwarth** [comment]
Hi Pat! We currently have a static check that prevents programmers from shooting themselves in the foot by Kleene-*ing a nullable expression, which would result in an infinite loop. This is a good thing.

But this static check doesn't prevent infinite loops from happening when you have parameterized rules, e.g.,

```
G {
  foo<x> = x*
  start = foo<"">
}
```

passes our static check but will loop forever if we try to use it on any input.

IMO we should leave the static check in there, because it's nice to detect mistakes early, but we should also implement a dynamic check that (say) throws an "bad kleene-* exception" when the expression under a Kleene-* succeeds w/o consuming any input. The message for this exception would explain that there is a problem in the grammar. What do you think?

(The place where I'd add this dynamic check is `pexprs.Iter.prototype.eval`, when `this.minNumMatches === 0`.)

**Comment by pdubroy** [comment]
Yes, sorry, should have been more clear. I know that we already have the static check as discussed above. I was suggesting an additional runtime check to catch things that the static check can't.

> IMO we should leave the static check in there, because it's nice to detect mistakes early, but we should also implement a dynamic check that (say) throws an "bad kleene-* exception" when the expression under a Kleene-* succeeds w/o consuming any input. The message for this exception would explain that there is a problem in the grammar. What do you think?
> 
> (The place where I'd add this dynamic check is pexprs.Iter.prototype.eval, when this.minNumMatches === 0.)

Yep, that sounds great. I wondered if it might be that easy, but I worried that there was something I was overlooking.

**Comment by alexwarth** [comment]
Fixed!
