### ISSUE TITLE
(E)BNF to Ohm?

### ISSUE THREAD

**Issue by strarsis** [harc/ohm#212]
@timfel: Is there a tool or way for converting existing (E)BNF (W3C) grammar to Ohm grammar?
E.g. from https://www.w3.org/TR/SVG/animate.html#TimingAttributes ?

**Comment by blakelapierre** [comment]
It should be possible to write a grammar to do the conversion. I'm not sure if one has already been written, though.

**Comment by strarsis** [comment]
@blakelapierre: Such a tool would be awesome and really save a lot of time and efforts.
There are many EBNF (W3C style) grammars in the Recommandations which can be used to AST and from AST just by copying and pasting them into that tool.

**Comment by pdubroy** [comment]
It would certainly be possible, but I'm not sure it's a good idea. Many (most?) context-free grammars cannot be converted mechanically to PEGs, because CFGs can be ambiguous, unlike PEGs. Also, Ohm's implicit space skipping (see [syntactic vs. lexical rules](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#syntactic-lexical)) is another thing that could cause problems.

E.g., taking the [Clock value grammar](https://www.w3.org/TR/SVG/animate.html#ClockValueSyntax) from the Animation spec you linked above, and just looking at this portion of the grammar...

```
Clock-val         ::= Full-clock-val | Partial-clock-val 
                      | Timecount-val
Full-clock-val    ::= Hours ":" Minutes ":" Seconds ("." Fraction)?
Partial-clock-val ::= Minutes ":" Seconds ("." Fraction)?
```

If we naively ported this to an Ohm grammar, then Partial-clock-val would accept things like `10 :05  .  3` — because Partial-clock-val begins with an uppercase letter, so it would skip spaces between its subexpressions.

In my experience, it's better to port grammars by hand, so that you can think about each rule as you convert it.

**Comment by strarsis** [comment]
@pdubroy: So the reason is that these EBNF W3C grammars are incomplete, would these be more complete, they would be automatically convertible to Ohm grammar?

**Comment by alexwarth** [comment]
I don't see Ohm's whitespace-skipping as a real problem here. If someone were writing the kind of translator @strarsis is talking about, they could make every rule a lexical rule, and skip whitespace explicitly wherever it made sense.

I agree with @pdubroy that ambiguity would be a problem. But not all CFGs are ambiguous, so maybe a good starting point is to translate the grammar naively (which would be straightforward to automate with Ohm). Then you could play with it in the Ohm Editor until it works as expected.

**Comment by strarsis** [comment]
@alexwarth: Are there good tutorials for translating the grammar from EBNF W3C to Ohm?
What would be the first steps for https://www.w3.org/TR/SVG/animate.html#TimingAttributes ?

**Comment by pdubroy** [comment]
@strarsis: By "ambiguous", I didn't mean that the grammars are incomplete — this has a more specific meaning in parsing theory: https://en.wikipedia.org/wiki/Ambiguous_grammar

**Comment by blakelapierre** [comment]
Here's my go at the EBNF grammar:

````
EBNF {
  Description = Rule*

  Rule = LHS Arrow RHS 
  
  Arrow = "⇐"
        | "<="

  LHS = lhsCharacter+
  lhsCharacter = alnum | "_"

  RHS = Repitition
      | Option
      | Choice
      | Sequence
      | word

  Repitition = "(" Item ")"

  Option = "[" Item "]"

  Choice = NonemptyListOf<Item, "|">

  Sequence = NonemptyListOf<Item, " ">

  word = character+
  character = lhsCharacter | "+" | "-"

  Item = word | RHS
}
````

It doesn't work properly though. It can't even parse the first example from the [EBNF paper](https://www.ics.uci.edu/~pattis/ICS-33/lectures/ebnf.pdf):

````
digit ⇐ 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
​
integer ⇐ [ + | - ] digit {digit}
              ^
>>Expected "]"
````

Changing the order of the items for RHS will cause errors in different places in the input string. I tried adding some other rules to fix some issues but then ran into other issues. Unless I'm missing something simple, I think writing an EBNF grammar might be significantly more complicated than the code above (which, I think is just a simple translation of the first two pages of the EBNF paper linked above).

**Comment by strarsis** [comment]
@blakelapierre: So in its current state, EBNF grammars can't be just re-used in ohm?

**Comment by strarsis** [comment]
@blakelapierre: So for making this grammar work out of the box, 
modifications to `ohm` itself would be required?

**Comment by blakelapierre** [comment]
For straight EBNF (or similar), I think a change is required (though, they
may conflict with existing goals), but there may be a way to emulate those
changes with additional grammar rules.

**Comment by strarsis** [comment]
It would be awesome if this W3C grammar could be somehow run in JavaScript and bidrectionally, 
whether using a modification in ohm or some conversion/adaptor tool.
So it is really just a matter of copying + pasting the rules and for immediately using them.

**Comment by pdubroy** [comment]
EBNF and Ohm's grammar language are essentially two different languages. They're similar, but their semantics differ in some key ways. It's a bit like, say, Java and C#.

So while it shouldn't be too hard to port most grammars from EBNF to Ohm, in the general case it's not possible to mechanical translate between the two languages. Any kind of conversion you could do would almost always require some debugging and tweaking to produce an equivalent grammar.

If you're looking for a JavaScript library for working with context-free grammars, maybe try [Jison](http://zaa.ch/jison/)?
