### ISSUE TITLE
Unexpected match

### ISSUE THREAD

**Issue by shrinktofit** [harc/ohm#234]
```
Ohm {
    BracedID
        = "{" (Identifier | BadID) "}"

    BadID(anything that isn't a right brace)
        = ((~"}") any)*

    Identifier
        = (letter | "_")#(listOf<(letter | "_" | digit),"">)
}
```
doesn't match the string
```
{DS_FUNC_*}

**Comment by pdubroy** [comment]
(Sorry for the extremely late response; I'm trying to clean up the older issues on here.)

This looks to be working as intended to me. Your `Identifier` rule will consume `DS_FUNC_` and then the parse will fail at `*`, because `}` is expected. You might be getting confused by Ohm's _ordered choice_ (`|`) operator, which will always use the first alternative that succeeds. This is the same as in other [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar)-based tools.
