### ISSUE TITLE
API Stability

### ISSUE THREAD

**Issue by christianbundy** [harc/ohm#235]
Hello! I've started using Ohm to parse simple URIs and I'm loving it, but after glancing at the contribution history it looks like development on Ohm may be ramping down. Are there plans to release version 1.0.0, and/or continue development on this project? Everything *looks* great, but I wanted to check in and make sure this project wasn't slowing down. Are there any resources where I could get updates on development?

**Comment by jakerockland** [comment]
Also curious about whether or not Ohm is still being actively developed/maintained. HARC is listed as a past project [here](https://www.ycr.org/). 

Not sure if that means that HARC is no longer operating or just no longer funded through YC.

**Comment by christianbundy** [comment]
cc: @pdubroy @alexwarth, specifically

**Comment by alexwarth** [comment]
Thanks for calling us out, @christianbundy. I guess we needed the extra push! :)

Thanks also for your kind words. It's always nice when we get feedback on Ohm, both critical and otherwise, and we really appreciate it.

While we haven't made any changes lately, I'm happy to report that I have been using Ohm quite a lot and I'm still very happy with it. That's not to say that I think the API is as good as it could be -- there are still some parts that bug me, e.g., how confusing optionals and iteration nodes can be to new users -- but overall I'm pretty happy with it.

I agree that this is a good time to start thinking about v1.0. I know that @pdubroy has been working on a hand-translation / rewrite of the Ohm implementation in TypeScript. Thinking about the types of various bits of the API should be interesting, and give us some insights that may turn into improvements.

Let me and Pat have a chat about this and we'll get back to you soon.

**Comment by christianbundy** [comment]
I appreciate the status update, thanks!
