### ISSUE TITLE
Add something like `=+` to match the existing `+=`

### ISSUE THREAD

**Issue by tonyg** [harc/ohm#265]
Currently, `+=` *prepends* a PEG to the supergrammar's rule.

We have been building a parser that uses inheritance to extend a grammar with error recovery productions, and find ourselves wishing for something like a `=+` that *appends* to the supergrammar's rule:

    SomeNT =+ SomeErrorRecoveryPEG
    // ... would be nice if it expanded to...
    SomeNT = Rules | From | The | SuperGrammar | SomeErrorRecoveryPEG

Would a patch implementing a `=+` operator be welcome?

Building on this question, if it were considered valuable to have both `+=` and `=+`, would it make any sense to have `+=` *append* and `=+` *prepend*?

Finally, if `=+` is a bad choice of operator, perhaps `|=` is a better choice for the appending variant?

**Comment by pdubroy** [comment]
Hi @tonyg!

I can see how this would be useful, and it's definitely something we have considered before. It would be nice if we could support this one way or another. That said, I do want to be cautious about adding new syntax.

In the past, we've also talked about supporting "super-send" — i.e., the ability to use `super` to apply the supergrammar's version of the current rule. E.g., `keyword += class` would be sugar for `keyword := class | super`. If we had that, I think you could then solve your case via `SomeNT := super | SomeErrorRecoveryPEG`. What do you think?

**Comment by tonyg** [comment]
I think having super-send is a great idea, yes! ... and could open the door even to *removing* (or deprecating, I suppose) the `+=` syntax :-)

Perhaps it should be spelled something like `^`, or other definitely-not-a-nonterminal, though? Presumably all this has already been discussed back and forth somewhere.

**Comment by alexwarth** [comment]
Hey @tonyg and @pdubroy!

The issue with "super" in Ohm is that it complicates the story of semantic actions. E.g., suppose we have the following grammars:

```
Parent {
  Foo = "foo"
}
```

```
Child <: Parent {
  Foo := ^Foo "bar"
}
```

I think we can all agree that the arity of `Child`'s `Foo` rule is 2, because we have the`^Foo` and the `"bar"`. So how do we specify how the value of `^Foo` is computed?

* Would the "semantic action dictionary" that we provide to `addOperation` need two entries for `Foo`? (One for `Parent`, and another for `Child`?)
* Or can we write a single semantic action that decides what to do based on `arguments.length`? (Ewwwww.)
* Or should we be forced to first create a semantics for the super-grammar, and then extend that semantics for the sub-grammar? And if so, how do we write the super-send in the semantic action, in JS? (I'm sure we can come up with something, but how nice can we make it?)

The `+=` operator and @tonyg's proposed `=+` operator circumvent these problems. So unless are some very useful things that we would be able to do with "super" that we can't do with those two, I think it's worth considering adding `=+` to Ohm.

What do you guys think?

**Comment by tonyg** [comment]
Interesting, I hadn't clicked to the semantics issue though I recognise it immediately as it crops up in our current workaround :-)

I wonder if something along the lines of a two-entries-for-Foo approach could work? Maybe, for semantics for grammars Parent and Child <: Parent, entries named "Foo" would be a fallback for "Parent_Foo" and "Child_Foo", which would be looked for first? Here we're starting to encode a rather peculiar object model, though...

What about an approach where `^Foo` is only allowed to appear on its own in a toplevel alternation in the extension?

So

    Foo := ^Foo | "bar"

would be permitted but

    Foo := ^Foo "bar"

forbidden?

That way we work around the issue: the existing label-the-branches approach could suffice.

    Foo := ^Foo             -- superKind
         | "bar" Zot "quux" -- zotKind

**Comment by pdubroy** [comment]
Right, the semantic action is the tricky part. I wrote up a proposal for this way back when (it took me a while to dig it up). At the time I'm not sure I considered the point about arity that you bring up, @alexwarth.

My proposal back then was inspired by Schärli-style traits. The idea was to either to support explicit renaming, like this:

```
CoolArithmetic <: Arithmetic with
        number as arithmeticNumber {
    number = arithmeticNumber | float
}
```

or to think of `super` as triggering an _implicit_ renaming, so that `number := super | float` would desugar to:

```
Arithmetic$number = /* original body of number in Arithmetic */
number = Arithmetic$number | float
```

I believe this sidesteps the issue of arity. It also gives a way to invoke the a super-operation (or attribute), which is kind of nice.

On the other hand, I still see the following problems:

- by renaming (implicit or explicit), you could turn a lexical rule into a syntactic one, and vice versa;
- with implicit renaming, it's unclear what the semantics of using it inside an inline rule declaration would be (e.g. `number := super  -- foo` — is that an application of the supergrammar's `number` rule or it's `number_foo` rule?)

**Comment by pdubroy** [comment]
In short I think this discussion has convinced me that an _append_ operator is indeed the simplest solution here. My vote would be for `|=` over `=+` though.

**Comment by pdubroy** [comment]
@tonyg: It took me a while to fully think through your suggestion of restricting where the super application can appear, but I think that could work.

**Comment by alexwarth** [comment]
@pdubroy, I agree that `|=` is a nice syntax for append.

Are we all on the same page then, and ready for a pull request from @tonyg? :)

**Comment by tonyg** [comment]
Close, I think!

Is it worth thinking more about the allow-super-sends-but-only-in-a-toplevel-alternation option? (I'd like to hear more about where you ended up in your thinking, @pdubroy. I can't seem to quite convince myself that the ergonomics of building semanticses will work out well...)

If not, then I'm up for making a PR to add `|=`!

**Comment by alexwarth** [comment]
My problem with the allow-super-sends-but-only-in-a-toplevel-alternation option is that would still have to provide different semantic actions for the same rule. E.g., in the grammars above you would need `Child_Foo` and `Parent_Foo`. In some even less fortunate examples, you'd also need `Grandparent_Foo`, `Greatgrandparent_foo`, etc.

**Comment by pdubroy** [comment]
I agree that having to write semantic actions for both `Child_Foo` and `Parent_Foo` is not great.

What if we supported something like `...` that represents inline expansion, rather than application, of the parent rule? I.e., `number += float` would be equivalent to `number := float | ...`, and then `number := ... | float` could be used instead of `|=`.

In such a declaration, we could enforce that every branch in the alternation has the same arity as those in the parent rule body, so there wouldn't be a need to write multiple semantic actions.

The advantage of this is that it could support both `+=` and `|=` in the same declaration:

```
foo := blah | ... | errorRecovery
```

That was my only remaining concern with `|=` — that there may be cases where you want to do both `+=` and `|=`. I don't have any concrete use cases though, so I'm also fine with going ahead with `|=`.

**Comment by alexwarth** [comment]
> What if we supported something like ... that represents inline expansion, rather than application, of the parent rule? I.e., number += float would be equivalent to number := float | ..., and then number := ... | float could be used instead of |=.

> In such a declaration, we could enforce that every branch in the alternation has the same arity as those in the parent rule body, so there wouldn't be a need to write multiple semantic actions.

I love this! I'll spend some time this weekend looking into how much work it would take to do this and report back.

(But I'm also happy with the `|=`.)

**Comment by pdubroy** [comment]
I took a crack at an implementation — see #267.

**Comment by pdubroy** [comment]
Closing this since the super-splice operator has landed. @tonyg, have you had a chance to give this a try?

**Comment by elgertam** [comment]
@pdubroy I have been working with @tonyg on the project he mentioned.

I really love the `...` syntax! I just tested it out on our parser, and it has cleaned up the one particularly hairy case where we had to copy-paste several lines from the parent grammar into the child grammar.

Unfortunately, most of the candidates for clean up couldn't be change due to arity checks in the semantics.

For example, let a parent grammar be

```ohm
FooGrammar {
  Foo = Bar+

  Bar = "<" Baz ">"

  Baz = letter+                   -- name
      | digit+ ("." digit+)?      -- number
}
```

with semantics

```javascript
const fooSemantics = {
  Foo(bar) {
    return bar.ast();
  },
  Bar(_oBrace, baz, _cBrace) {
    return baz.ast();
  },
  Baz_name(id) {
    return id.sourceString;
  },
  Baz_number(whole, _dot, frac) {
    return parseFloat(this.sourceString);
  }
};
```
.

I would like to define a child grammar

```ohm
SonOfFooGrammar <: FooGrammar {
  Bar := ...
       | errorLine   -- error

  Baz := ...
       | (~">" any)+ -- error

  errorLine = nonnl+ (lineTerminator | end)

  nonnl = ~lineTerminator any
  lineTerminator = "\n" | "\r"
}
```

with semantics

```javascript
const sonOfFooSemantics = {
  ...fooSemantics,
  Bar_error(_err){
    console.warn(`Parse error: Bar: \`${this.sourceString}\``);
  },
  Baz_error(_err){
    console.warn(`Parse error: Baz: \`${this.sourceString}\``);
  },
};
```
.

However, because of the arity rules, I have to instead define `SonOfFooGrammar` as

```ohm
SonOfFooGrammar <: FooGrammar {
  Bar := "<" Baz ">" -- nonError
       | errorLine   -- error

  Baz := ...
       | (~">" any)+ -- error

  errorLine = nonnl+ (lineTerminator | end)

  nonnl = ~lineTerminator any
  lineTerminator = "\n" | "\r"
}
```

with semantics

```javascript
const { Bar: _Bar, ...sonOfFooSemantics } = {
  ...fooSemantics,
  Bar_nonError: fooSemantics.Bar,
  Bar_error(_err){
    console.warn(`Parse error: Bar: \`${this.sourceString}\``);
  },
  Baz_error(_err){
    console.warn(`Parse error: Baz: \`${this.sourceString}\``);
  },
};
```
.

This isn't so bad (though I find this usage of ES6's destructuring assignment to be a bit too clever).

I personally would find it quite elegant for the extension to work as in the former case, though I don't (yet) know enough about Ohm's internals to know how feasible this change would be. If there's no reason why this wouldn't work, I could begin working on a PR.

Regardless, I love the new super-slice feature and I think it can be quite useful going forward. 

I'm also curious about the Schärli-style traits mentioned above. Tony and I had independently discussed something like "traits" for Ohm, and both of us thought a feature like that would be useful.
