### ISSUE TITLE
Difference between my project code and Ohm Editor with the same grammar and input

### ISSUE THREAD

**Issue by 7pri2** [harc/ohm#270]
Hello, I used the editor to write my grammar and when I copy it in my project, the result is not the same as in the editor.
This is my grammar: 
```
IPFilter {
    Expr =
        "(" Expr ")" -- parenthesis
        | Expr "and" Expr -- and
        | Expr "or" Expr -- or
        | "!" Expr --not
        | IP
    Filter =
        digit+ "-" digit+ -- range
        | digit+
    IP = Filter "." Filter "." Filter "." Filter
}
```
and the input `!(0.0.0.1 or 1.2.3.4) and 2.3.1.3` produces the following AST
![image](https://user-images.githubusercontent.com/25961291/100769811-d861df00-33fc-11eb-9a54-728643518981.png)
However, the same input in my code misses parenthesis and `!` nodes.
Did I miss something ?

**Comment by pdubroy** [comment]
Hi @7pri2, can you explain what you mean by "the same input in my code misses parenthesis and `!` nodes."? E.g., can you describe what you expected to happen and what actually happened?

**Comment by 7pri2** [comment]
I expected to get the AST in the screenshot, but what I got was the same AST but without the _Expr -- parenthesis_ and the _Expr -- not_, so when I use ohm.extras.toAST, I get:
- Expr -- and
    - Expr -- or
        - IP
    - IP

instead of the following AST I expected

- Expr -- and
    - Expr -- not
        - Expr -- parenthesis
            - Expr -- or
                - IP
                - IP
    - IP

**Comment by pdubroy** [comment]
Ah, I see.

The visualizer shows the _concrete_ syntax tree (or parse tree), whereas `toAST` returns an _abstract_ syntax tree. The difference is basically that the AST is higher-level representation. E.g., you might change the syntax of your language to use `not` instead of `!`, but the representation in the AST would not change.

Make sense?

I'll go ahead and close this since it doesn't appear there is an actual bug here, but please feel free to reopen if I'm wrong.
