### ISSUE TITLE
Implementing hoisting

### ISSUE THREAD

**Issue by sinkovsky** [harc/ohm#278]
I am writing a transpiler from my DSL to Javascript.

Is it possible to implement a Semantics which would hoist variable definitions to the top?

I tried defining two operations, but I couldn't find a way to 'skip' some nodes inn the operation, so it could be used in the following:
```
BlockDefinition(identifier, body) {
   return `function ${identifier.transpile()}() {
          ${body.extractVariables()}
          
          ${body.transpile()}
  }`;    
}
```

**Comment by alexwarth** [comment]
Hi Sergey,

Wouldn't it suffice to make `extractVariables` do nothing for nodes that
are not declarations? (Well, for nested blocks you'd probably want to
return the declarations that are inside, etc.)

Best,
Alex

**Comment by sinkovsky** [comment]
Hi Alex,

I tried just returning empty strings for nodes that are not variable declarations, but because Expressions inside the block are IterationNodes I am getting extra commas in the resulting source code.
I tried to find documentation on _iter() action but couldn't find any.

**Comment by pdubroy** [comment]
Hi @sinkovsky,

Expanding a bit on what @alexwarth said, I would approach this by writing an operation with:
- an action for every kind of node that can introduce a binding (e.g. `VariableDeclaration`)
- a default `_nonterminal` action, which merges the declarations of all its child nodes (this is the hoisting part); and
- an action for functions (e.g. `FunctionBody`) which prevents hoisting above the function boundary.

BTW, I'd be tempted to separate the extraction part from the codegen. In other words, I'd probably make `extractVariables` return a `Set<string>` representing all the variables, and do the codegen at the function boundary.

Regarding iteration nodes: getting extra commas in your output sounds like you may be doing string concatenation on an array. E.g., if your grammar has something like: `Block = "{" Statement* "}"`, and an action looks something like this:

```
Block(_open, statements, _close) {
    return statements.extractVariables(); // Returns an Array of strings
}
```

...then it's important to note that this is return an _array_ of strings. That's because Ohm's default handling of iteration nodes maps the operation over the list of nodes.

One option would be — as it sounds like you're suggesting — to specify an `_iter` action. This takes one argument: an array of child nodes. You could then ensure that this action returns a string. (The other option is to detect the iteration nodes in the parent action using the `isIteration()` method.)

Hope that helps! BTW, feel free to join us [on Discord](https://discord.gg/KwxY5gegRQ) or the [mailing list](https://groups.google.com/u/2/g/ohm-discuss) for more help or to discuss design choices.

**Comment by pdubroy** [comment]
I took a crack at implementing a `hoistDeclarations` operation for our ES5 grammar: https://github.com/harc/ohm/commit/1a3a00c6653bd555881b7be27fc02c3e5a17c539. Happy to hear any feedback that either of you have.

@sinkovsky, maybe this is useful to you. Since this is just an example, it's possible it's not quite the right solution, but it should at least be a good starting point.

I'm going to go ahead and close this issue, but please feel free to discuss further on the mailing list or Discord!

**Comment by sinkovsky** [comment]
@pdubroy Thank you very much for detailed explanations and example. That helped a lot.
