### ISSUE TITLE
disallow whitespaces in rule

### ISSUE THREAD

**Issue by aleclofabbro** [harc/ohm#298]
how can I constraint a rule to not allow whitespaces?
e.g. I'd like 
```ohm 
type = alnum+
id = alnum+
typeId = type "/" id
```
`typeId` to accept 
```
a2b/c4d
```
but not 
```
a2b / c4d
```

**Comment by pdubroy** [comment]
The way you've written it here will not allow whitespace.

Ohm does implicit whitespace skipping inside of rules whose name begins with a capital letter. So, if you were to name the rule `TypeId` (rather than `typeId`) then it would skip spaces.

You can read more here: https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#syntactic-lexical
