### ISSUE TITLE
export grammar as module string

### ISSUE THREAD

**Issue by aleclofabbro** [harc/ohm#300]
when defining grammar that uses escaped characters as a js string
e.g.:
```js
const grString = `
Grammar {
// ...more grammar here

lineTerminator = "\n" | "\r" | "\u2028" | "\u2029"

// ...more grammar here
}
`

ohm.grammar(grString)
```

with 
```
/node_modules/ohm-js/src/main.js:283
    throw errors.grammarSyntaxError(m);
    ^

Error: Line 68, col 20:
> 68 |  lineTerminator = "
                          ^
" | " " | " "
Expected "\"", not "\n", or an escape sequence

```

Although it works as expected when : 
- reading the grammar from a file
- grammar doesn't use escaped chars 

note that `lineTerminator` is taken from ohm's javascript grammar example

**Comment by pdubroy** [comment]
You have to be careful when writing Ohm grammars inside of a JavaScript string literal. The `\n` here is an [escape sequence](https://mathiasbynens.be/notes/javascript-escapes) that is replaced with a literal newline character before Ohm sees the string.

It's especially since Ohm supports many of the same escape sequences as JavaScript, so you have to be mindful of which level is interpreting your escape!

There are two solutions:
- Use `String.raw`:
  ```
  const grString = String.raw`
      lineTerminator = "\n"
      ...
  `
- Or, use a double backslash everywhere you want a single backslash to appear in the Ohm grammar:
  ```
  const grString = `
      lineTerminator = "\\n"
  `
  ```
