### ISSUE TITLE
Lookahead operator issue

### ISSUE THREAD

**Issue by aleclofabbro** [harc/ohm#301]
Seems like [Lookahead operator](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#lookahead-) doesn't work properly,     
test in editor the example from doc : `letter &digit` will match `'a9'`   
```
Gr{
  A = letter &digit
}
 ```
against `a9` and the parser complaints `Expected end of input` after `a`

**Comment by yoshikiohshima** [comment]
The lookahead operator does not consume input. it tests if the next input matches with the specified rule, but keeps the input pointer intact.  In a way a grammar is ill-specified if it ends with lookahead as it won't match with any input.

**Comment by aleclofabbro** [comment]
thanks @yoshikiohshima, it makes sense,    
but I still see some issue:     
- It would be good to document these details 
- the example on docs doesn't work

moreover I tested against your suggestion with no luck:

```
Gr{
  A =  &digit letter 
}
``` 
with `9a` results in `Expected a letter` on `9` position

```
Gr{
  A =  letter &digit letter 
}
``` 
with `a9a` results again in `Expected a letter` on `9` position

**Comment by pdubroy** [comment]
Hi @aleclofabbro,

Agreed that we should improve the documentation if we can! The [syntax reference](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#lookahead-) currently says the following about lookhead:

> Succeeds if the expression expr can be matched, but does not consume anything from the input stream. Usually used as part of a sequence, e.g. letter &digit will match 'a9', but only consume 'a'.

If you can suggest an improvement here, I'm happy to update it.

Regarding your example, can you describe what you are trying to do with lookahead? Dicussing a concrete example might make it easier to explain.

**Comment by pdubroy** [comment]
Here's a working example, similar to your first grammar, that demonstrates how lookahead works:

```
G {
  start = letterBeforeDigit digit
  letterBeforeDigit = letter &digit
}
```

When matching, `letterBeforeDigit` will match against "a9", but only consume the "a". But some other rule then has to consume the digit (e.g., the `digit` at the end of `start` here).

**Comment by aleclofabbro** [comment]
well,  I was not trying to achieve any syntax feature, at the moment...     
Currently many of my grammar rules use a number of cosmetic expression tokens that action functions just ignore       
so I just wanted to leverage the `&` operator to cleanup and simplify my actions signatures, removing informationless arguments and keeping just the meaningful ones

**Comment by pdubroy** [comment]
Ok, unfortunately lookahead won't help with that.

This is a key aspect of Ohm's design that helps keep a clean separate between the grammar and its semantic actions. If the semantic actions didn't have access to everything that is matched, then it would sometimes be necessary to modify the grammar in order to implement different kinds of semantic actions.

**Comment by aleclofabbro** [comment]
ok, that definitely makes sense,      
I won't attempt for that kind of cleanup then..

but, apologize, I still don't grok the point with it, could please explain :

> G {
>  start = letterBeforeDigit digit
>  letterBeforeDigit = letter &digit
> }
> When matching, `letterBeforeDigit` will match against "a9", but only consume the "a".

yes, I understand the first digit (`9`) after the letter won't be consumed      
but apart from what is consumed and focusing on matching:    
I would expect `start` to match `a90` (2 digits after letter) as the inlined version of start would be `start = letter &digit digit`     
instead, testing on online editor at least, both `start` and  `letterBeforeDigit` match only  against  `letter digit` pattern, and `start` won't match a `letter digit digit` pattern

thanks for your time !

**Comment by yoshikiohshima** [comment]
As the inline version of start would be `start = letter &digit digit`, it would exactly match one letter and one digit.

While a grammar rule is typically understood as a declarative "is" statement ("start **is** a rule with a letter followed by digit"), lookahead may be better understood as an operational "does" statement. What `&digit` does is that it checks if the next part of input matches with the specified rule `digit`, and if it doesn't it fails.  But if it does match... it effectively does not do anything but move on.  Note that what the rule `digit` does. it checks if the next part of input matches, and if it does match, consumes the part of input, otherwise it fails.  So `&digit digit` is exactly the same as `digit`, except that the check is done twice at the same input location.

With Ohm, where the semantic rule is clearly separated from the grammar rule, I'd say that lookahead is less commonly needed, unless if you have a somewhat weird grammar.  An example is like the classic "context free grammar cannot count but PEG can" one. If your grammar needs nested parenthesis whose number has to be equal to the number of letters inside:

(a)
((ab))
(((abc)))
(((xyz)))

and so on.  You can write such a grammar with lookahead.

**Comment by aleclofabbro** [comment]
cool !
this one really made me understand ..     
main misunderstanding was about the word `consume` ...
I thought that `consuming` a token was referring at semantic-action-layer, whilst it's at matching stage .
Thanks !
