### ISSUE TITLE
Functions as arguments of semantic actions

### ISSUE THREAD

**Issue by mlajtos** [harc/ohm#318]
Would it be possible to alter args to semantic action to be functions with extra properties, or in general make them callable? It would look like this:

```js
const semantics = g.createSemantics().addOperation('eval', {
  Exp(e) {
    return e();
  },
  AddExp(e) {
    return e();
  },
  AddExp_plus(left, op, right) {
    return left() + right();
  },
  AddExp_minus(left, op, right) {
    return left() - right();
  },
  PriExp(e) {
    return e();
  },
  PriExp_paren(open, exp, close) {
    return exp();
  },
  number(chars) {
    return parseInt(this.sourceString, 10);
  }
});
```

In my opinion, this looks cleaner than always repeating name of the semantic action in non-terminal node actions. The same thing applies for defining actions for `ohm.extras.toAST`. And it can be backward-compatible.

**Comment by pdubroy** [comment]
Hi @mlajtos,

Sorry it's taken me a while to respond to this! I was focusing on getting the [v16 release](https://github.com/harc/ohm/releases/tag/v16.0.0) out.

In principle this is something that we could support, and I'm pretty sure we discussed it back when we designed the first version of Ohm's semantics.

How would it work in the presence of multiple operations? E.g., if you had not just an `eval` operation, but also a `prettyPrint` operation? I guess one option would be that a call like `left()` would be shortcut for `left.eval()`, but you could also use `left.prettyPrint()` to invoke an operation other than the one that you're in.

However, that approach would have some challenges. Currently, the wrappers (which are passed in to the semantic actions — so-called because they wrap a CST node) are an instance of a class which inherits from the super semantics. That's how we implement inheritance of operations. I don't think that's compatible with making the wrappers callable.

Also, I think this would mean allocating a separate object for every (operation, CST node) pair. whereas right now we only need one per CST node.

Overall my feeling is that the tradeoffs wouldn't be worth it. The current approach also has the advantage that it's explicit and easy to explain.

**Comment by mlajtos** [comment]
Hello @pdubroy,

don't worry – I am happy to see new release with TS support. :)

> How would it work in the presence of multiple operations? E.g., if you had not just an eval operation, but also a prettyPrint operation? I guess one option would be that a call like left() would be shortcut for left.eval(), but you could also use left.prettyPrint() to invoke an operation other than the one that you're in.

Yes, exactly. This way it would be backward-compatible, while less verbose for single-operation semantics.

> Overall my feeling is that the tradeoffs wouldn't be worth it. The current approach also has the advantage that it's explicit and easy to explain.

Totally understandable. :) Thank you for consideration.
