### ISSUE TITLE
# operator not working on syntactic rule inside lexical rule

### ISSUE THREAD

**Issue by Lamby777** [harc/ohm#345]
I feel like I'm doing something wrong, but I read the docs 5 times and couldn't find a fix. Is this a bug? This error stays, even if I use the # example inside the [syntax reference](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md). I'm trying to use "Expression" inside this lexical rule.

![image](https://user-images.githubusercontent.com/35111165/148157662-278e501f-3afd-47e4-8ba2-f006ff781cbb.png)

**Comment by pdubroy** [comment]
Up to now, this was disallowed because it's _usually_ a grammar smell if you are trying to apply a syntactic rule inside a lexical context — see #136 for a discussion.

As of Ohm v16.1.0 (just released), you can now use the built-in [`applySyntactic`](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#applySyntactic) rule to do this.

Note that `#` is for the opposite: it creates a _lexical_ context in a syntactic rule body.
