### ISSUE TITLE
Character in the middle of a sentence is not matched

### ISSUE THREAD

**Issue by ericmorand** [harc/ohm#372]
I'm trying to separate a "sentence" into three tokens, by using an arbirrary character as separator.

Basically, I want to provide a grammar that support that kind of syntax:

`Foo consists of n Bar`

And have the lexer detect three tokens:

* `Foo consists of`
* `n`
* `Bar`

Writing the following rule fails:

```
Test {
	Expression = alnum+ "n" alnum+
}
```

> foo consists of n bar
> Expected "n" or an alpha-numeric character

It definitely looks like a bug because something like:

```
Test {
	Expression = "n" alnum+
}
```

Would totally detect two tokens here:

`n bar`

**Comment by pdubroy** [comment]
This is a common confusion about how the `+`/`*` operators work in Ohm (and other PEG-based tools). The problem is that your `alnum+` expression will consume the `n` character. You can use negative lookahead to prevent this: `(~"n" alnum)+`.

See [Dealing with greedy matching](https://ohmjs.org/docs/patterns-and-pitfalls#dealing-with-greedy-matching) on the _Patterns and Pitfalls_ page for more details.
