### ISSUE TITLE
Avoid naming rules (different arity)

### ISSUE THREAD

**Issue by stephano33** [harc/ohm#380]
Again, I'm a very big fan of Ohm. Especially, the GUI is perfect!

I'm now generating grammars the I want to debug with the Ohm GUI to find errors.
Those grammars don't have any semantic rules; i.e., I'm only debugging the syntax rules.

```
AddExp
    = AddExp "+" MulExp  
    | MulExp

```
Is there a way to write such Ohm grammars? I'd like to avoid naming the first choice as '-- plus'. Or use implicit auto-generated names, like '-- rand123'?

I guess there is no such way but I though to ask first.

**Comment by stephano33** [comment]
Also, there needs to be a NewLine ("\n") before the '|', right? I mean when "inline rule declarations" are used.

This doesn't work:
```
ab = "a" --a | ("b" "c") -- ac
```

**Comment by stephano33** [comment]
Another problem from today.

How could I name the different arity rules of "factor"?
```
factor = value ("*" sp  factor  | "/" sp  factor | sp)
sp = " "*
value = digit+

```
This doesn't work:
`factor = value ("*" sp  factor -- mult  | "/" sp  factor -- division | sp --space)`

It is always possible (but looks silly) to change the arity with dummy rules, like this:
`factor = value ("*" sp  factor  | "/" sp  factor | sp sp sp)`

Here: " sp sp sp" is just a dummy way to make the rarity homogeneous.

**Comment by MuhammedZakir** [comment]
You'll have to move the bracketed part to another rule.
```
factor  = value factor_
factor_ = "*" sp factor  -- mult
        | "/" sp factor  -- div
        | sp
```

**Comment by pdubroy** [comment]
Hi @stephano33,

Glad you are enjoying Ohm! Btw, for questions like these, it's probably better to ask under [Discussions](https://github.com/harc/ohm/discussions) or over in the [Ohm Discord](https://discord.gg/KwxY5gegRQ).

To your questions:

> Is there a way to write such Ohm grammars? I'd like to avoid naming the first choice as '-- plus'. Or use implicit auto-generated names, like '-- rand123'?

No, most people using Ohm will need semantic actions, and consistent arity is required for the semantic actions to work, so we don't support omitting the case names. What's the reason you don't want to name them?

> Also, there needs to be a NewLine ("\n") before the '|', right? I mean when "inline rule declarations" are used.

Yes, when using inline rules, you need to separate them by a newline. In case it's helpful, you can look at [the grammar that defines Ohm's grammar syntax](https://github.com/harc/ohm/blob/master/packages/ohm-js/src/ohm-grammar.ohm#L70). 😄

(I'm going to go ahead and close this since it's not an actual issue within Ohm, but feel free to ask more questions on the discussion board or Discord!)
